### ISSUE TITLE
Add form field for ORDERED list of things

### ISSUE THREAD

**Issue by timbl** [solid/solid-ui#100]
We have a the `Multiple` field for letting the users add zero or more new objects to the data graph.  We need the same thing, but adding an ordered list, with the ability re-arrange the elements of the list.

The code produced   should like like   `<subject> <property> ( <x> <y> <z>  ) .`

Then when this is sone we can 
- change the form form to use this for editing the `parts` list of a form itself
- obsolete the part/sequence way of making forms 

This will also be useful for many things from music playlists to ordered photo lists, ordered author lists, and so on.

**Comment by timbl** [comment]
Currently this is looking like a    ` ui:ordered true; ` addition to the functionality of `Multiple`. 

See https://github.com/solid/solid-ui/pull/157  (WIP)

**Comment by megoth** [comment]
This was resolved in https://github.com/solid/solid-ui/pull/162
