### ISSUE TITLE
409 Error when attempting to edit Profile Highlight Color

### ISSUE THREAD

**Issue by kevin-howard-jd** [solid/solid-ui#105]
If you attempt to edit the Highlight Color on your Profile, you get an error:
`Web error: 409 (Conflict) on PATCH of <https://khoward5.dev.inrupt.net/profile/card>`

## To Replicate
1. Log into a dev.inrupt.net Pod.
2. "Edit your profile".
3. Edit the Highlight Color. 

## Expected Behaviour
1. The Highlight color is updated to the selected color.

## Actual Behaviour
1. Error `Web error: 409 (Conflict) on PATCH of <https://khoward5.dev.inrupt.net/profile/card>` is displayed.

**Comment by Vinnl** [comment]
Tim said in chat that it's fine to delete that line, because it's apparently weird that it's there in the first place.
