### ISSUE TITLE
Cannot Add Address, Email or Phone to Profile

### ISSUE THREAD

**Issue by kevin-howard-jd** [solid/solid-ui#106]
When editing my dev.inrupt.net Profile, I cannot add a new Address, Email, or Phone.

## To Replicate
1. Log into a dev.inrupt.net Pod.
2. "Edit your profile".
3. Click on green + next to Address, Email, or Phones.

## Expected Behaviour
1. A new Address, Email, or Phone is added to the Profile.

## Actual Behaviour
1. Nothing visible happens.
2. In Console, an error is displayed:
``forms.js:194 Uncaught TypeError: r.newThing is not a function
    at HTMLTableRowElement._ (forms.js:194)``

**Comment by Vinnl** [comment]
Apparently this was also fixed by #95.
