### ISSUE TITLE
Start migration to TypeScript

### ISSUE THREAD

**Issue by megoth** [solid/solid-ui#126]
We've introduced TypeScript in other projects for the data browser, and have had success with this. We've also had some bugs in this project that would've been discovered with TypeScript.

We should migrate with ease though, as the current code base of this project is a bit difficult to untangle. This issue is about setting up the initial tooling to enable TypeScript, and making sure that it doesn't break any current APIs and resources that we currently produce.

**Comment by bourgeoa** [comment]
Is it not a good idea to first migrate to lerna all mashlib project, like IPS is doing ?

Multi-repo projects are rather complicated to follow and manage as I can see with mashlib and IPS.

**Comment by megoth** [comment]
We're already using Lerna in [mashlib-dev](https://github.com/inrupt/mashlib-dev). It only uses parts of Lerna's functionality though, so it's not a full-fledged mono-repo. The reason is that some projects are fully stand-alone libraries (such as [linkeddata/rdflib](https://github.com/linkeddata/rdflib.js)), so we cannot package it as a mono-repo anyway.
