### ISSUE TITLE
Take out prettier-standard

### ISSUE THREAD

**Issue by timbl** [solid/solid-ui#158]
Suggest removing use of prettier-standard and just using eslint to check

- prettier-standard has a bug which makes break eslint and then complain about it
- prettier-standrad *unlike prettier* is dangerous in that without any `write` or `fix` parameter it will overwrite you files.
- prettier-standard complains about say a let which should be  const but won't fix it
- There are command line problems if you try to just check one file it seems to process them all
- It checks HTML but doesn't have an option for polyglot which we should be using ideally

Any format checker we use must  have the --fix option to fix things automatically, so prettier-standard can't do that with let > const it seems

**Comment by megoth** [comment]
This was done in the corresponding PRs:

- https://github.com/solid/mashlib/pull/81
- https://github.com/solid/solid-panes/pull/200
- https://github.com/solid/solid-ui/pull/161
- https://github.com/solid/chat-pane/pull/23
- https://github.com/solid/folder-pane/pull/8
- https://github.com/solid/source-pane/pull/4
- https://github.com/solid/contacts-pane/pull/11
- https://github.com/solid/issue-pane/pull/11
- https://github.com/solid/meeting-pane/pull/4
- https://github.com/solid/pane-registry/pull/3
