### ISSUE TITLE
Decouple from mashlib

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-ui#176]
I tried to use the `lib/create.js` file that is created when you run `npm run build` in https://github.com/solid/meeting-pane/pull/7, but got this error:
```sh
Uncaught ReferenceError: require is not defined
    at create.js:11
(anonymous) @ create.js:11
```
I think that's because solid-ui relies on https://github.com/solid/mashlib/blob/master/src/index.ts#L35-L37

**Comment by megoth** [comment]
`npm run build` are usually triggering tools like Babel or Webpack - I think it's more correct to use create.js and other modules you need to bundle them, or run in an environment that supports CJS (like Node)

**Comment by michielbdejong** [comment]
I worked it out, now have webpack builds for both MeetingPane and ChatPane
