### ISSUE TITLE
Inaccurate tooltip to add new tool

### ISSUE THREAD

**Issue by csarven** [solid/solid-ui#203]
Under `src/create.js:newThingUI`, https://github.com/solid/solid-ui/blob/ff45c7afb5c7218e871f0239ee30daaa60b92fc3/src/create.js#L49 I don't think "Add another tool to the meeting" is accurate. "Add another tool" may be sufficient.

**Comment by michielbdejong** [comment]
How about a 3 minute turn around on bug fixes ;)
