### ISSUE TITLE
Webpack build problems on Windows

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-ui#213]
Break-out issue about how @SharonStrats can't get the build to work on the buttons branch.
See https://github.com/solid/solid-ui/pull/204#pullrequestreview-361609968 for the screenshot.
@SharonStrats looking at https://github.com/solid/solid-ui/blob/master/package.json#L12 it's the `npm run build-lib` step that is failing to produce the `./lib/index.js` which is needed by the subsequent `npm run build-webpack` step. Can you try:
* `npm run build-lib`
* Check if ./lib/index.js exists
* If so, it can be used by `npm run build-webpack` which should produce ./lib/webpack-bundle.js.

**Comment by scenaristeur** [comment]
Hi all, 
npm run  build does not work for me on Windows 10 

```
    "build-version": "sh ./timestamp.sh > src/versionInfo.ts  && eslint \"src/versionInfo.ts\" --fix",
...
    "clean": "rm -rf lib",
```
because there is no "rm" nor "sh" commands
