### ISSUE TITLE
Update rdflib version to 1.07-4?

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-ui#238]
Should we update solid-ui to depend on rdflib@1.0.7-4? Doing so would resolve one issue I had, but introduce lots of other breaking tests, but looks like it might be simple to fix in a single place:

> Argument of type 'import("/Users/michiel/gh/solid/solid-ui/node_modules/rdflib/lib/tf-types").NamedNode' is not assignable to parameter of type 'import("/Users/michiel/gh/solid/solid-ui/node_modules/rdflib/lib/named-node").default'.

**Comment by megoth** [comment]
It would be good to test the latest version of rdflib, for sure. But then I think it's also important that whatever versions we release that depends on prereleases of rdflib should also be a prerelase, i.e. it's for testing purposes. We should try to push a "proper" release of rdflib soon, and with that we can release "proper" versions of dependent projects as well.

**Comment by theRealImy** [comment]
This is an old ticker. Rdflib is now at 2.2.6 already.
