### ISSUE TITLE
Rename confusing `store` parameter to `doc`

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-ui#244]
A lot of functions in src/widgets/forms.ts have `store` as their 6th positional argument.
However, despite the naming collision, this parameter is unrelated to `UI.store`.
Instead, it should be a `NamedNode` for the fetchable RDF source where data about `subject` (the 4th positional argument) should be "stored". This is clearly confirmed by the fact that https://solid.github.io/solid-ui/Documentation/forms-intro.html refers to the 6th positional argument as `doc`.

So I'll rename all these from `store` to `doc`, and then I can also rename the global `uiStore` to just `store`, the same was as it is in other files.

**Comment by theRealImy** [comment]
Old ticket.
