### ISSUE TITLE
Fix code after new types are merged into rdflib

### ISSUE THREAD

**Issue by megoth** [solid/solid-ui#301]
There has been [work to fix some type errors we've had in the prereleases of rdflib](https://github.com/linkeddata/rdflib.js/pull/406). The branch [rdflib-typing-fix](https://github.com/solid/solid-ui/tree/rdflib-typing-fix) should handle the corresponding update we need to do for this repo - the remaining is (hopefully) just to update to the proper version of rdflib.

**Comment by SharonStrats** [comment]
Just tracking that in tabs.test.ts, I believe there is one using lit.  Just need to add language.
