### ISSUE TITLE
Is there a rationale for differentiating between internal and external links?

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-ui#317]
Thinking about a UI for displaying linked data I was wondering if there is a rationale for differentiating links to same and cross origins

1. Most browser dont let you easily switch from one origin to another, for example in the address bar.  So that might mean that clicking/opening a link may be a different work flow / UX

2. I seem to recall, but cant find it that the original UDI by @timbl had different colour links.  Possibly green and blue.  

See:

> Q: I'm a student of visual communications and asked myself why links are blue. I found some answers that might be, for example blue is a color of learning, but I'm not sure what is right. Is there any reason, why links are colored blue ?

> A: There is no reason why one should use color, or blue, to signify links: it is just a default. I think the first WWW client (WorldWideWeb I wrote for the NeXT) used just underline to represent link, as it was a spare emphasis form which isn't used much in real documents. Blue came in as browsers went color - I don't remember which was the first to use blue. You can change the defaults in most browsers, and certainly in HTML documents, and of course with CSS style sheets. There are many examples of style sheets which use different colors.

> My guess is that blue is the darkest color and so threatens the legibility least. I used green whenever I could in the early WWW design, for nature and because it is supposed to be relaxing. Robert Cailliau made the WWW icon in many colors but chose green as he had always seen W in his head as green.

> https://www.w3.org/People/Berners-Lee/FAQ.html

I suppose each data browser will have it's own style.  But I was curious about how the defaults for the original web of documents was designed.  

Perhaps blue links for same origin and green for cross origin, or the other way round?

**Comment by timbl** [comment]
This is interesting, yes, as there is a trust thing that you can assume you can trust things on the same origin.  Of course some web sites have a warning message "Warning you are leaving this site -- are you sure".   Mind you there are times in solid when your work is spread across a few domains of your colleagues, and which pod the target is on is not relevant so this would be confusing.

This is really a question for browsers in general, not just RDF browsers.
Closed as interesting but not an issue for solid-ui
