### ISSUE TITLE
mashlib 1.4.0 display incorrect name's pod (port number in lieu of pod's owner)

### ISSUE THREAD

**Issue by bourgeoa** [solid/solid-ui#318]
@michielbdejong 

pod's name appears to be the port number : 
![image](https://user-images.githubusercontent.com/2218470/87532405-61b58680-c693-11ea-9f90-f83a355eb40f.png)

used to be : 
![image](https://user-images.githubusercontent.com/2218470/87532751-e3a5af80-c693-11ea-87fa-d447f14ff9c9.png)

**Comment by bourgeoa** [comment]
This appears to be only on your pod.
On my pod that was created earlier on NSS v5.3.0 the correct name is displayed.

When I create a new pod on NSS v5.4.0 https://alain.solid.community:8443 the name is also correctly displayed.

So it is not really a bug.
Maybe you did set the name  as "8443" when creating the pod ?

I shall close the issue

**Comment by michielbdejong** [comment]
Ah yes, that's just the Full Name I set for that webid, see https://michielbdejong.solid.community:8443/profile/card#me
