### ISSUE TITLE
public profile view broken

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-ui#319]
Open a private browsing tab and compare https://michielbdejong.solid.community:8443/profile/card#me
to https://michielbdejong.solid.community/profile/card#me.
In the first one, none of the data is appearing.

**Comment by bourgeoa** [comment]
I also have this bug, the first time I click on `edit your profile`.
![image](https://user-images.githubusercontent.com/2218470/87542473-48b4d180-c6a3-11ea-9ca1-c1cfd9ccba93.png)

When I go to https://alain.solid.community:8443/profile/card#me everything seems correct.
Clicking to `edit your profile` the above error has disapeared.

**Comment by michielbdejong** [comment]
I see this (no data filled in):
<img width="828" alt="Screenshot 2020-07-15 14 23 11" src="https://user-images.githubusercontent.com/408412/87544444-bf9f9980-c6a6-11ea-8d9e-206a0182dbde.png">

**Comment by bourgeoa** [comment]
There was no data. I filled some and you should see them.
![image](https://user-images.githubusercontent.com/2218470/87597905-e1bf0900-c6f2-11ea-903a-4c4693132985.png)

**Comment by michielbdejong** [comment]
Ah right, indeed! :)
It's just the difference between `vcard:name` and `foaf:name`, see https://github.com/solid/solid-panes/pull/39.
