### ISSUE TITLE
link to doc in readme

### ISSUE THREAD

**Issue by scenaristeur** [solid/solid-ui#321]
Documentation

See https://solid.github.io/solid-ui/Documentation/api/ for the API documentation

--> no api in Documentation

**Comment by SharonStrats** [comment]
I will have a look, but in the mean time if you have solid-ui on your machine you can run npx serve and go to http://localhost:5000/examples/ and you can see examples.  This is not 100% complete as we are still working on it, but there are quite a few.

**Comment by scenaristeur** [comment]
It'good to have example in readme, so we can see what we can do before cloning & installing 🙂

**Comment by theRealImy** [comment]
The examples are mentioned in the readme and the https://solid.github.io/solid-ui/Documentation/api/ works again.
