### ISSUE TITLE
no rm or sh command on Windows for npm run build

### ISSUE THREAD

**Issue by scenaristeur** [solid/solid-ui#322]
Hi all, 
npm run  build does not work for me on Windows 10 

```
    "build-version": "sh ./timestamp.sh > src/versionInfo.ts  && eslint \"src/versionInfo.ts\" --fix",
...
    "clean": "rm -rf lib",
```
because there is no "rm" nor "sh" commands

**Comment by SharonStrats** [comment]
Hi @scenaristeur you just need to run the build in Windows bash instead of command line and it should work. If you have any problems just replay to this issue.
