### ISSUE TITLE
get rid of confusing 'Olivier' from www.solidcommunity.net page

### ISSUE THREAD

**Issue by mariadimou** [solid/solid-ui#393]
Olivier was very smart to name his pod 'www' but now we all suffer from 
www.solidcommunity.net showing the appended confusing page 
instead of being an alias of solidcommunity.net.

Many CERN users were totally put off by this situation. 
I discussed this with @jeff-zucker and @timbl in the https://gitter.im/solid/solidos channel on April 13th 2021. 
They agreed it should be fixed. 

See screenshot. 
![Screenshot from 2021-04-20 19-15-52](https://user-images.githubusercontent.com/26465927/115438283-8126a480-a20d-11eb-8b77-99d3ff003f9a.png)
![Screenshot from 2021-04-20 19-20-08](https://user-images.githubusercontent.com/26465927/115438299-85eb5880-a20d-11eb-8d61-ca131c5461ae.png)

**Comment by Vinnl** [comment]
I happened to have reported this too, but in the solidcommunity.net issue tracker: https://github.com/solid/solidcommunity.net/issues/34

I copied your report to there.

**Comment by bourgeoa** [comment]
@mariadimou 
wwwsolidcommunity.net pod has been removed after checking it was really void.
It was created before the blacklist was implemented. Cannot be recreated.
