### ISSUE TITLE
RDF browser

### ISSUE THREAD

**Issue by nin-jin** [solid/solid-ui#45]
Current UI is very poor. Would you like to make new UI on [$mol](http://mol.js.org) technology? I just have wrote a RDF browser as example:  http://mol.js.org/app/rdf/

**Comment by timbl** [comment]
It looks as though the RDF version linked above has been discontinued.  The main UI framework seems alive at https://mol.js.org/app/ and https://mol.js.org/app/demo/-/
Closed as interesting related work but not being incorporated in solid-ui.

**Comment by nin-jin** [comment]
It's moved to http://rdf.hyoo.ru/
