### ISSUE TITLE
Notepad is displaying black font with a black background = black box

### ISSUE THREAD

**Issue by TorontoBoy** [solid/solid-ui#52]
I have created a Notepad in my Public folder. As an authenticated user I can input and save as normal, and it all looks fine. But viewing from an unauthenticated user my notepad content looks like a big black box. The reason is that the font is black (colour #222)and the background is also black (colour #111). If I change the background colour to #ffffff white, I can then see my text.

Example: https://dontai.inrupt.net/public/Introduction/
There is text on lines 1,2,4,and 6. Highlight any of these lines and you will see the text.

![solid-notepad-black-lines-2018-10-01 23-00-45-cropped](https://user-images.githubusercontent.com/30269457/46533445-9b2c5180-c872-11e8-814d-5d10612eb85e.png)

After around 10 minutes the background colour changes to background-color: #fed0f7; and text colour color: black; , and I can see the text. These new colours match what I see if I am authenticated and can edit the document. After 10 minutes the text and background colours are completely different from when I first display the page. The page changes colours by itself and without me touching the window. This is very odd.

![solid-notepad-black-lines-after-10-mins-2018-10-05 08-01-04](https://user-images.githubusercontent.com/30269457/46534107-1262e500-c875-11e8-85ea-17a264d7eb7d.png)

**Comment by JordanShurmer** [comment]
The pink background is actually an indicator that an update didn't go through properly.

**Comment by JordanShurmer** [comment]
Fixed by PR #54 if someone could take a look 😃
