### ISSUE TITLE
Fallback for http and unauthorized sources

### ISSUE THREAD

**Issue by chrysn** [solid/solid-ui#58]
When using the facetted browser to display data where following your nose leads outside the scope of solid pots, one encounters statically hosted RDF that is either unavailable to HTTPS, not having CORS headers, or having CORS headers sufficient for "regular operation" but not for requests with credentials (eg. `Access-Control-Allow-Origin: *`).

As the facetted browser provided within the Solid UI is the best successor to the Tabulator Of Old, and thus is (at least, also) usable as a generic RDF browsing tool, I suggest that the dereferencing operation on follow-your-nose'd resources should at least try to fetch them without sending credentials (thus helping with `Access-Control-Allow-Origin: *` resources). If that's what causes the error on http-only resources, it'd also help there (and would probably not be the fallback but the default on obviously unauthenticated resources).

Catering for non-CORS resources is harder, and can probably be left out as most providers hopefully ship at least the basic headers on their public data -- it'd be nice-to-have but probably inconvenient to set up (and not run on public instances).

**Comment by megoth** [comment]
I'm wondering if such a mechanism could be implemented having a proxy-API as part of LDP.

1) Trying to fetch a resource using the APIs in the browser,
2) Failing because of reasons you've mentioned, will look for proxy-API (discovery-mechanism is another discussion, but could be through .well-known and/or maybe exposed in a RDF-profile for the server),
3) proxy-API will try to fetch resource on your behalf

I haven't thought this well-through, just suggesting. Pinging @RubenVerborgh, @kjetilk and @timbl in case they have some thoughts on this.

Btw @chrysn, you might want to move this issue to another repo; If people agree to my suggestion, maybe https://github.com/solid/solid-spec is a good place. Let's see the response first, and then maybe move.

**Comment by chrysn** [comment]
> I'm wondering if such a mechanism could be implemented having a
> proxy-API as part of LDP.

Proxying should, as I understand the situation currently, not be a major
part of the solution.

Applications on HTTPS can easily fetch pages that set the nowadays
common COSE headers[1], both when they're served on HTTP and HTTPS; it's
only problematic when the client requests credentials to be sent.

Once the web client has fallback[2] from sending credentials to not
sending any, proxying becomes a niche requirement for accessing
documents that don't send any CORS headers at all.


[1]: Access-Control-Allow-Origin: *, and some selected AC-Allow-Headers
values -- basically (in my understanding) what browsers needed to work
around broken sites that didn't respect GET being safe. Might be a good
idea to explicitly list those as best practice to ontology authors ...
somewhere? (it's not directly solid related).

[2]: That fallback process might, in future, entail further user
interaction that leads to the server whitelisting that origin for that
user on that server, but that shouldn't stand in the way of the fallback
process.

**Comment by megoth** [comment]
> Proxying should, as I understand the situation currently, not be a major part of the solution. 

Yeah, you're right, I've been a bit fixtured on doing changes to the LDP spec in general today, I'll hold my horses =P

Nevertheless, it would be nice to have a standard way of doing this that various Solid servers could implement. That was my main point initially.

**Comment by timbl** [comment]
I think the fallback you suggest, @chrysn, has been in the code for a while. (and for while it has console flagging it).  It also needs refactoring to be clearer and just laid out using async and await.   But I'll close this as the fallback to no credentials is there in the fetcher.
```
 setCredentials: https://www.w3.org/People/Berners-Lee/card starts as: undefined
mashlib.js:9005    setCredentials: https://www.w3.org/People/Berners-Lee/card ends as: include
mashlib.js:8993  setCredentials: https://www.w3.org/People/Berners-Lee/card starts as: include
mashlib.js:9005    setCredentials: https://www.w3.org/People/Berners-Lee/card ends as: include
```
I'll close this issue as it is implemented.
