### ISSUE TITLE
No permission to access inbox

### ISSUE THREAD

**Issue by kristophor** [solid/solid-ui#63]
You are currently logged in as https://kristophor.solid.community/profile/card#me, but do not have permission to access https://kristophor.solid.community/inbox/.

<img width="1664" alt="Screen Shot 2019-05-06 at 11 21 11 AM" src="https://user-images.githubusercontent.com/7058039/57235560-17e20280-6ff1-11e9-8cb8-c5549a035cd3.png">

**Comment by megoth** [comment]
Can you tell us more about the background of this? E.g. did you try to change access to this resource, or did it happen "out of the box"?

**Comment by kristophor** [comment]
My apologies.

1. clear browser data
2. login into https://kristophor.solid.community/
3. click inbox
4. error shows "You are currently logged in as https://kristophor.solid.community/profile/card#me, but do not have permission to access https://kristophor.solid.community/inbox/."

**Comment by megoth** [comment]
What I need to understand is if you've done anything to the inbox resource that might warrant this behavior, or if it's a bug.

Could you create a new account and see if the same happens there? If not, I would simply suggest that [you delete your pod](https://kristophor.solid.community/account/delete) - it does require that you added your email as part of the creation process though. You should be able to recreate your account with the same username afterwards.

I would've liked to point you to the support of solid.community, but it doesn't seem to be anyone doing that at the moment. Will update https://github.com/solid/information/blob/master/pod-providers.md when (or rather, if) I'm unable to figure it out.

**Comment by melvincarvalho** [comment]
@kristophor just checking if this is still an issue.  Since it was raised there's been some new releases and bug fixes

**Comment by kristophor** [comment]
not an issue anymore thanks
