### ISSUE TITLE
Forms UI should remove user input UI when resource not editable

### ISSUE THREAD

**Issue by timbl** [solid/solid-ui#88]
Forms are useful as read-only controls, when the user is not allowed to change the data.  However, it is confusing to have things like UI for adding new data, and 'save text' buttons in this case.

  When the document with the data is not editable by the user, then remove all edit ability from the UI.   This is already done with checkboxes, like

```
  const editable = UI.store.updater.editable(doc.uri)
```

Possibly: add options parameter to the form API to allow the caller to explicitly turn off editing.

**Comment by timbl** [comment]
To work well this is dependent on https://github.com/linkeddata/rdflib.js/issues/332

**Comment by megoth** [comment]
This was fixed in https://github.com/solid/solid-ui/pull/95
