### ISSUE TITLE
Stop specific sharing pane on /(root) deletes .acl

### ISSUE THREAD

**Issue by bourgeoa** [solid/solid-ui#94]
on NSSv5 and sure for v5.1.6 and v5.1.7: 
- `Stop specific sharing pane on /public` deletes `.acl` and your cannot edit it anymore (404).
- If you try to go to `/(root)` and `Set the sharing of folder content`, it does not recreate .acl in /public

In fact you can even **Stop specific sharing pane on /(root) it deletes .acl and you are out of your pod**

>  No ACL found for https://alain.bourgeoa.ga:8517/, searched in 
>  - https://alain.bourgeoa.ga:8517/.acl

I already submitted this issue # 1257 on solid/node-solid-server on july, 6

**Comment by megoth** [comment]
Aoch, good find! We should try to at least prevent that from being done with the data browser. But yeah, need to be programmatically impossible on the server as well, good call ^_^

**Comment by bourgeoa** [comment]
- I looked into the code and it seems to me that a way to do it is `acl-control.js` not to display the `Stop specific sharing for this` by including after L584 a :

> test that 
-- if( ! ( targetACLDoc.uri.endsWith('/.acl') && ( is in /(root) || is in first level folder (/public, /settings, ...) ) ))

- The same can be done in node-solid-server in `Idp.js` at `function delete`, but it does not avoid the use of `fetch(targetACLDoc.uri, options(DELETE ...))` which is what rdflib.js uses.

**Comment by megoth** [comment]
Fixed in https://github.com/solid/solid-ui/pull/96
