### ISSUE TITLE
Can create a folder at /(root) level but not edit the related .acl

### ISSUE THREAD

**Issue by bourgeoa** [solid/solid-ui#99]
I created a test container at /(root) level `/test` and am unable to edit `/test/.acl` with the sharing pane : error 404.

It goes with issue #94 . When you `stop specific sharing for  /public` you delete `/public/.acl` and you never can edit it anymore (error 404).

I suppose that it needs to change `/.acl` to make it a usable default or to create `/test/.acl` on error 404 in sharing pane

**Comment by megoth** [comment]
@timbl but are you able to do that when you create a folder on root?
